# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78681cc2d825eb2fece95f09be98aba89466d16e62c8d2f3c7963314d50f3c2a66e08148dc1dbefad76aa11f9c00f4c4767f4f18a3f5df9bf06fe392efc7b68f

test:
  secret_key_base: b3918a066d843125c842f06be22ad647c8f80515c078358da7dd62530fa49caa01524eb550c0fce3c6e764128a49a436cafd9769898929eb846e2a4d13ac391d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
